name: CI/CD
on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: ghactions-codenoobs
  AZURE_WEBAPP_PACKAGE_PATH: build
  NODE_VERSION: 14.x
  ARTIFACT_NAME: react-webapp

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install, Build & Tests 🔧✅
        run: |
          npm install
          npm run-script build 
          npm run-script test

      - name: Upload Built WebApp ⬆
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  staging:
    name: Deploy to STG
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://ghactions-codenoobs-staging.azurewebsites.net
    steps:
      - name: Download Built WebApp ⬇
        uses: actions/download-artifact@v1
        with:
          name: ${{ env.ARTIFACT_NAME }}

      - name: Deploy to Azure WebApp 🚀
        uses: azure/webapps-deploy@v2
        id: deploy_staging
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          slot-name: staging

  deploy:
    name: Deploy to PRD
    needs: staging
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://ghactions-codenoobs.azurewebsites.net
    steps:
      - name: Download Built WebApp ⬇
        uses: actions/download-artifact@v1
        with:
          name: ${{ env.ARTIFACT_NAME }}

      - name: Deploy to Azure WebApp🚀
        id: deploy_production
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
