name: Master CI/CD
on:
  push:
    branches:
      - master

env:
  PACKAGE_PATH: ./build
  NODE_VERSION: 14.x
  ARTIFACT_NAME: react-webapp

jobs:
  build-and-deploy:
    name: Build&Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install, Build & Tests 🔧✅
        run: |
          npm install
          npm run-script build 
          npm run-script test

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: master
          build_dir: ${{ env.PACKAGE_PATH }}
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}