name: PR CI
on:
  pull_request:
    types: [opened, edited, synchronize]

env:
  NODE_VERSION: "14.x"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install, Build & Tests 🔧✅
        run: |
          npm install
          npm run-script build 
          npm run-script test --if-present

  qa:
    name: Deploy to QA
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Publish on GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
